# Generated by Django 5.2.13 on 2026-04-30 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('DOB', models.DateField(db_column='DOB')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('email_address', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CUSTOMER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiscountRate',
            fields=[
                ('member_type', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Student', 'Student')], max_length=50, primary_key=True, serialize=False)),
                ('discount_rate', models.FloatField()),
            ],
            options={
                'db_table': 'DISCOUNT_RATE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('gift', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PRODUCTS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'STORE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('house', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('town_city', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('England', 'England'), ('Scotland', 'Scotland'), ('Wales', 'Wales'), ('Northern Ireland', 'Northern Ireland')], max_length=50)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='store.customer')),
            ],
            options={
                'db_table': 'ADDRESSES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GiftCards',
            fields=[
                ('gift_card_num', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('issue_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('redeemed_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='gift_cards', to='store.customer')),
            ],
            options={
                'db_table': 'GIFT_CARDS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HomeFragrances',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='home_fragrance', serialize=False, to='store.products')),
                ('product_type', models.CharField(choices=[('Scent Diffuser', 'Scent Diffuser'), ('Air Freshener', 'Air Freshener'), ('Scented Candles', 'Scented Candles'), ('Room Sprays', 'Room Sprays'), ('Reed Diffusers', 'Reed Diffusers')], max_length=50)),
                ('bundle', models.BooleanField()),
            ],
            options={
                'db_table': 'HOME_FRAGRANCES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('restocking_threshold', models.IntegerField(default=10)),
                ('last_restocking_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_items', to='store.products')),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory', to='store.store')),
            ],
            options={
                'db_table': 'INVENTORY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_ren_date', models.DateField(blank=True, null=True)),
                ('customer', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='membership', to='store.customer')),
                ('member_type', models.ForeignKey(db_column='member_type', on_delete=django.db.models.deletion.DO_NOTHING, to='store.discountrate')),
            ],
            options={
                'db_table': 'MEMBERSHIP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=50)),
                ('order_type', models.CharField(choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup')], max_length=50)),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Paypal', 'Paypal')], max_length=50)),
                ('installment', models.BooleanField(default=False)),
                ('total_payment', models.FloatField()),
                ('gift_card', models.ForeignKey(blank=True, db_column='gift_card_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='store.giftcards')),
            ],
            options={
                'db_table': 'ORDERS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='phonenumbers', to='store.customer')),
            ],
            options={
                'db_table': 'PHONE_NUMBERS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_images', to='store.products')),
            ],
            options={
                'db_table': 'PRODUCT_IMAGES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonalFragrances',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='personal_fragrance', serialize=False, to='store.products')),
                ('size', models.CharField(max_length=20)),
                ('fragrance_family', models.CharField(choices=[('Floral', 'Floral'), ('Oriental', 'Oriental'), ('Woody', 'Woody'), ('Fresh', 'Fresh'), ('Citrus', 'Citrus'), ('Chypre', 'Chypre')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('strength', models.CharField(choices=[('Eau de Parfum', 'Eau de Parfum'), ('Eau de Toilette', 'Eau de Toilette'), ('Parfum', 'Parfum')], max_length=20)),
                ('engraving', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'PERSONAL_FRAGRANCES',
                'managed': True,
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.customer')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.products')),
            ],
            options={
                'db_table': 'FAVOURITE',
                'managed': True,
                'unique_together': {('customer', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='baskets', to='store.customer')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='basket_items', to='store.products')),
            ],
            options={
                'db_table': 'BASKET',
                'managed': True,
                'unique_together': {('customer', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OrderRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.products')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.orders')),
            ],
            options={
                'db_table': 'ORDER_REF',
                'managed': True,
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.products')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='store.orders')),
            ],
            options={
                'db_table': 'ORDER_ITEMS',
                'managed': True,
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Instalments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalment_number', models.IntegerField()),
                ('instalment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_due', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Late', 'Late')], default='Pending', max_length=50)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.orders')),
            ],
            options={
                'db_table': 'INSTALMENTS',
                'managed': True,
                'unique_together': {('order', 'instalment_number')},
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.customer')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.orders')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.products')),
            ],
            options={
                'db_table': 'PLACES',
                'managed': True,
                'unique_together': {('customer', 'product', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(db_column='inventory_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.inventory')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='store.products')),
            ],
            options={
                'db_table': 'PRODUCT_INVENTORY',
                'managed': True,
                'unique_together': {('inventory', 'product')},
            },
        ),
    ]
