# Generated by Django 5.2.13 on 2026-05-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_update_addresses_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='store.products'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
        migrations.AlterField(
            model_name='giftcards',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='homefragrances',
            name='product',
            field=models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='home_fragrance', serialize=False, to='store.products'),
        ),
        migrations.AlterField(
            model_name='instalments',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='store.orders'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='store.products'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='store.store'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='customer',
            field=models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.ForeignKey(db_column='member_type', on_delete=django.db.models.deletion.CASCADE, to='store.discountrate'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.orders'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
        migrations.AlterField(
            model_name='orderref',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='store.orders'),
        ),
        migrations.AlterField(
            model_name='orderref',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='gift_card',
            field=models.ForeignKey(blank=True, db_column='gift_card_num', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.giftcards'),
        ),
        migrations.AlterField(
            model_name='personalfragrances',
            name='product',
            field=models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal_fragrance', serialize=False, to='store.products'),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='phonenumbers', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='places',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='places',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='store.orders'),
        ),
        migrations.AlterField(
            model_name='places',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.products'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='inventory',
            field=models.ForeignKey(db_column='inventory_id', on_delete=django.db.models.deletion.CASCADE, to='store.inventory'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
    ]
