# Generated by Django 5.2.13 on 2026-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_addresses_customer_alter_basket_customer_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='discountrate',
            constraint=models.CheckConstraint(condition=models.Q(('member_type__in', ['Standard', 'Premium', 'Student'])), name='valid_member_type'),
        ),
    ]
