# Generated by Django 5.2.14 on 2026-06-03 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_add_membership_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptier',
            options={'managed': True, 'ordering': ['monthly_price']},
        ),
        migrations.AddField(
            model_name='membership',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discountrate',
            name='discount_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.ForeignKey(blank=True, db_column='member_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.discountrate'),
        ),
    ]
