# Generated by Django 5.2.15 on 2026-06-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Paypal', 'Paypal'), ('Cash', 'Cash')], max_length=50),
        ),
    ]
