# Generated by Django 5.2.15 on 2026-06-08 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='store.customer')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='store.products')),
            ],
            options={
                'db_table': 'WISHLIST',
                'managed': True,
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
