# Generated by Django 5.2.15 on 2026-06-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='region',
            field=models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('EU', 'European Union')], default='US', max_length=2),
        ),
    ]
