# Generated by Django 5.2.15 on 2026-06-09 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_products_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragranceAccord',
            fields=[
                ('accord_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bar_color', models.CharField(blank=True, help_text='Hex color for display', max_length=7)),
                ('font_color', models.CharField(blank=True, default='#FFFFFF', max_length=7)),
            ],
            options={
                'db_table': 'FRAGRANCE_ACCORD',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FragranceNote',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(blank=True, max_length=100)),
                ('group', models.CharField(blank=True, help_text='e.g. Woods and mosses, Flowers, Citrus', max_length=50)),
                ('odor_profile', models.TextField(blank=True)),
                ('icon_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'FRAGRANCE_NOTE',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfumer',
            fields=[
                ('perfumer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'PERFUMER',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='personalfragrances',
            name='description',
            field=models.TextField(blank=True, help_text='HTML description from Fragrantica'),
        ),
        migrations.AddField(
            model_name='personalfragrances',
            name='fragrance_url',
            field=models.CharField(blank=True, help_text='Fragrantica page URL', max_length=500),
        ),
        migrations.AddField(
            model_name='personalfragrances',
            name='main_photo_url',
            field=models.CharField(blank=True, help_text='Primary bottle image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='personalfragrances',
            name='rating_avg',
            field=models.FloatField(blank=True, help_text='Average rating (0-5)', null=True),
        ),
        migrations.AddField(
            model_name='personalfragrances',
            name='rating_count',
            field=models.IntegerField(blank=True, help_text='Total number of ratings', null=True),
        ),
        migrations.AddField(
            model_name='personalfragrances',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalfragrances',
            name='reviews_count',
            field=models.IntegerField(blank=True, help_text='Total number of written reviews', null=True),
        ),
        migrations.AlterField(
            model_name='personalfragrances',
            name='fragrance_family',
            field=models.CharField(blank=True, choices=[('Floral', 'Floral'), ('Oriental', 'Oriental'), ('Woody', 'Woody'), ('Fresh', 'Fresh'), ('Citrus', 'Citrus'), ('Chypre', 'Chypre'), ('Fougère', 'Fougère'), ('Leather', 'Leather'), ('Aromatic', 'Aromatic'), ('Gourmand', 'Gourmand')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalfragrances',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Unisex', 'Unisex')], default='Unisex', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalfragrances',
            name='strength',
            field=models.CharField(blank=True, choices=[('Eau de Parfum', 'Eau de Parfum'), ('Eau de Toilette', 'Eau de Toilette'), ('Parfum', 'Parfum'), ('Eau de Cologne', 'Eau de Cologne'), ('Perfume Oil', 'Perfume Oil'), ('Body Mist', 'Body Mist'), ('Hair Mist', 'Hair Mist')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductAccord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.FloatField(default=0, help_text='0-100 percentage')),
                ('accord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to='store.fragranceaccord')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_accords', to='store.products')),
            ],
            options={
                'db_table': 'PRODUCT_ACCORD',
                'ordering': ['-percentage'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('layer', models.CharField(choices=[('top', 'Top'), ('middle', 'Middle / Heart'), ('base', 'Base')], max_length=10)),
                ('opacity', models.FloatField(default=1.0, help_text='Visual prominence 0.0-1.0')),
                ('weight', models.FloatField(default=1.0, help_text='Visual size on pyramid chart')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to='store.fragrancenote')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_notes', to='store.products')),
            ],
            options={
                'db_table': 'PRODUCT_NOTE',
                'ordering': ['layer', '-opacity'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductPerfumer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perfumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumer_products', to='store.perfumer')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_perfumers', to='store.products')),
            ],
            options={
                'db_table': 'PRODUCT_PERFUMER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('appreciation', 'Appreciation'), ('longevity', 'Longevity'), ('sillage', 'Sillage / Projection'), ('season', 'Season'), ('time_of_day', 'Time of Day'), ('price_value', 'Price Value'), ('gender_votes', 'Gender Votes')], max_length=20)),
                ('vote_label', models.CharField(help_text='e.g. love, like, moderate, strong, winter', max_length=50)),
                ('votes_count', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_votes', to='store.products')),
            ],
            options={
                'db_table': 'PRODUCT_VOTE',
                'ordering': ['vote_type', '-votes_count'],
                'managed': True,
            },
        ),
    ]
