# Generated by Django 5.2.15 on 2026-06-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_fragrantica_enrichment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('store', 'product')},
        ),
    ]
