# Generated by Django 5.2.15 on 2026-06-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalfragrances',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='personalfragrances',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image',
        ),
        migrations.AddField(
            model_name='productimages',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productimages',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='fragrantica_id',
            field=models.IntegerField(blank=True, help_text='Fragrantica PID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='fragrantica_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='main_photo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='rating_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='reviews_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HomeFragrances',
        ),
        migrations.DeleteModel(
            name='PersonalFragrances',
        ),
    ]
