# Generated by Django 5.2.15 on 2026-06-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_personal_home_fragrances'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='similar_products', to='store.products')),
                ('similar_product', models.ForeignKey(db_column='similar_product_id', on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='store.products')),
            ],
            options={
                'db_table': 'SIMILAR_PRODUCT',
                'managed': True,
                'unique_together': {('product', 'similar_product')},
            },
        ),
    ]
