# Generated by Django 5.2.15 on 2026-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_add_similar_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragrancenote',
            name='group_color',
            field=models.CharField(blank=True, default='#8B7355', help_text='Hex color for note group display', max_length=7),
        ),
    ]
