# Generated by Django 5.2.15 on 2026-06-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_add_note_group_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_ml', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'PRODUCT_VARIANT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_symbol', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'REGION',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='instalments',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='instalments',
            name='order',
        ),
        migrations.RemoveField(
            model_name='phonenumbers',
            name='customer',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='region',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='giftcards',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='giftcards',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcards',
            name='redeemed_at_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_redemptions', to='store.store'),
        ),
        migrations.AddField(
            model_name='giftcards',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_gift_cards', to='store.customer'),
        ),
        migrations.AddField(
            model_name='giftcards',
            name='redemption_channel',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Store', 'Store')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='giftcards',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='store.customer'),
        ),
        migrations.AlterField(
            model_name='giftcards',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giftcards',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.products'),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='orderitems',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='basket',
            name='variant',
            field=models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='store.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='variant',
            field=models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('customer', 'variant')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitems',
            unique_together={('order', 'variant')},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='region',
            field=models.ForeignKey(db_column='region_code', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.region'),
        ),
        migrations.AddField(
            model_name='products',
            name='regions',
            field=models.ManyToManyField(related_name='products', through='store.ProductVariant', to='store.region'),
        ),
        migrations.DeleteModel(
            name='Instalments',
        ),
        migrations.DeleteModel(
            name='PhoneNumbers',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size_ml', 'region')},
        ),
    ]
